# Generated by Django 3.1 on 2020-10-02 15:44

from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='name')),
                ('sub_title', models.CharField(max_length=300, verbose_name='sub title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True)),
                ('direction_of_use', models.TextField(blank=True, null=True)),
                ('top_seller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('option_name', models.CharField(blank=True, max_length=255, null=True)),
                ('option_value', models.CharField(blank=True, max_length=200, null=True)),
                ('shopify_rest_variant_id', models.CharField(blank=True, max_length=355, null=True)),
                ('shopify_storefront_variant_id', models.CharField(blank=True, max_length=355, null=True)),
                ('date_first_available', models.DateField(blank=True, null=True)),
                ('date_last_modified', models.DateField(auto_now=True, null=True)),
                ('claims', models.TextField(blank=True, null=True)),
                ('discontinued', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('ingredients', models.ManyToManyField(to='product.Ingredient', verbose_name='ingredients')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stockist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='where-to-buy/logos')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, upload_to=product.models.Tag.icons_directory_path)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='WhereToBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('stockist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.stockist')),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wheretobuy', to='product.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=product.models.ProductImage.image_directory_path)),
                ('image_type', models.CharField(blank=True, choices=[('PI', 'Product Image'), ('LS', 'Life Style'), ('RP', 'Range Photo'), ('OT', 'Others')], max_length=2)),
                ('image_angle', models.CharField(blank=True, choices=[('FRONT', 'Front'), ('BACK', 'Back'), ('ANGLE', 'Angle'), ('TOP', 'Top'), ('RIGHT-SIDE', 'Right Side'), ('LEFT-SIDE', 'Left Side'), ('BOTTOM', 'Bottom'), ('CUSTOM', 'Custom')], max_length=10)),
                ('alternate_text', models.CharField(max_length=250)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='product.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(blank=True, to='product.ProductType', verbose_name='types'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('background_image_alt', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True)),
                ('products', models.ManyToManyField(blank=True, related_name='collections', to='product.Product')),
            ],
        ),
    ]
