# Generated by Django 3.1 on 2020-09-02 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='ProductType',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='shopify_variant_reference_number',
            new_name='shopify_variant_id',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='main_claim',
            new_name='sub_title',
        ),
        migrations.AlterField(
            model_name='product',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='product.product'),
        ),
    ]
