# Generated by Django 3.1 on 2020-09-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200902_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='sub_title',
            field=models.CharField(max_length=300, verbose_name='sub_title'),
        ),
    ]
