# Generated by Django 3.1 on 2020-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201009_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='inventory_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='rrp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
