# Generated by Django 3.1 on 2020-09-18 12:32

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200917_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='main_image',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='tags',
            field=models.ManyToManyField(blank=True, to='product.Tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='types',
            field=models.ManyToManyField(blank=True, to='product.ProductType', verbose_name='types'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.ImageField(blank=True, upload_to=product.models.Tag.icons_directory_path),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='name'),
        ),
    ]
