# Generated by Django 3.1 on 2020-09-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200918_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shopify_variant_id',
            new_name='shopify_rest_variant_id',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shopify_storefront_variant_id',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
