# Generated by Django 3.1 on 2020-09-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200922_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='sub_title',
            field=models.CharField(max_length=300, verbose_name='sub title'),
        ),
    ]
