# Generated by Django 3.1 on 2020-09-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200928_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='top_seller',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
    ]
