# Generated by Django 3.1 on 2021-05-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210504_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=4869, unique=True, verbose_name='slug'),
        ),
    ]
