# Generated by Django 3.1 on 2021-05-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210511_1050'),
        ('product', '0011_auto_20210505_1349'),
    ]

    operations = [
    ]
