# Generated by Django 3.1 on 2021-06-02 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210511_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['image_type']},
        ),
        migrations.RemoveField(
            model_name='collection',
            name='products',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=2970, unique=True, verbose_name='slug'),
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Leave it as 0 if you wish for this item to go to the beginning of the list. or set a big number and it will automatically will order it at the end of the list.')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectionitem', to='product.product')),
            ],
            options={
                'index_together': {('product', 'order')},
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='collection', to='product.CollectionItem'),
        ),
    ]
