# Generated by Django 3.1 on 2021-06-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210602_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='collection_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='product.collection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='item',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collected_items', to='product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, to='product.CollectionItem'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=5211, unique=True, verbose_name='slug'),
        ),
        migrations.AlterIndexTogether(
            name='collectionitem',
            index_together={('item', 'order')},
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='product',
        ),
    ]
