# Generated by Django 3.1 on 2021-06-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210617_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='product.Ingredient', verbose_name='ingredients'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=8039, unique=True, verbose_name='slug'),
        ),
    ]
