# Generated by Django 3.1 on 2021-09-19 19:52

from django.db import migrations, models
import product.utils


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20210629_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitem',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=product.utils.get_slug, unique=True, verbose_name='slug'),
        ),
    ]
