# Generated by Django 3.1 on 2021-10-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_auto_20211011_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='compare_at_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='euro_compare_at_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='euro_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
