# Generated by Django 3.1 on 2022-03-07 12:40

from django.db import migrations, models


def set_all_products_public(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    Product.objects.all().update(is_public=True)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_productvariant_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='top_seller',
        ),
        migrations.AddField(
            model_name='product',
            name='graphql_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='graphql_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.RunPython(
            code=set_all_products_public,
            reverse_code=migrations.RunPython.noop,
        )
    ]
