# Generated by Django 3.1 on 2022-05-23 13:17

from django.db import migrations, models
import django.db.models.deletion


def update_product_main_images(apps, schema_editor):
    Product = apps.get_model('product', 'Product')
    ProductImage = apps.get_model('product', 'ProductImage')
    main_images = ProductImage.objects.filter(main=True).select_related('variant')
    for main_image in main_images:
        Product.objects.filter(id=main_image.variant.product_id).update(main_image=main_image)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20220509_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_product', to='product.productimage'),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_product', to='product.productimage'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(
            code=update_product_main_images,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
