# Generated by Django 3.1 on 2022-07-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0038_auto_20220523_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
