# Generated by Django 3.1 on 2022-09-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_productimage_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='graphql_id',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='shopify_rest_variant_id',
            field=models.CharField(max_length=355, unique=True),
        ),
    ]
