# Generated by Django 3.1 on 2023-03-08 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20230130_1644'),
        ('product', '0041_auto_20230305_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.slider'),
        ),
    ]
