# Generated by Django 3.1 on 2022-07-25 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_productimage_updated'),
        ('user', '0003_auto_20211101_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(db_index=True, unique=True)),
                ('email', models.EmailField(max_length=256)),
                ('reminder_date', models.DateTimeField()),
                ('email_sent', models.BooleanField(default=False)),
                ('bought_variants', models.ManyToManyField(to='product.ProductVariant')),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=1024)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReminderBoughtVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('review_reminder', models.ForeignKey(db_column='reviewreminder_id', on_delete=django.db.models.deletion.CASCADE, to='user.reviewreminder')),
                ('variant', models.ForeignKey(db_column='productvariant_id', on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
            ],
            options={
                'unique_together': {('review_reminder', 'variant')},
            },
        ),
    ]
