# Generated by Django 3.1 on 2022-12-16 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_productinstockreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinstockreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
