# Generated by Django 3.2.20 on 2024-01-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('user', '0014_sessioncookie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonReviewReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField()),
                ('email_sent', models.BooleanField(default=False)),
                ('amazon_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reminders', to='orders.amazonorder')),
            ],
        ),
    ]
