# Generated by Django 3.2.20 on 2023-09-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_sessioncookie'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('template_name', models.CharField(choices=[('review-reminder', 'Review Reminder'), ('subscribe-invitation', 'Subscribe Invitation')], max_length=128)),
                ('send_time', models.DateTimeField(db_index=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sentemail',
            name='template_name',
            field=models.CharField(choices=[('in-stock', 'In Stock'), ('review-reminder', 'Review Reminder'), ('review-approval', 'Review Approval'), ('subscribe-invitation', 'Subscribe Invitation')], max_length=128),
        ),
    ]
