# Generated by Django 3.2.20 on 2024-01-16 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_amazonreviewreminder'),
        ('user', '0015_user_mobile_number'),
    ]

    operations = [
    ]
