# Generated by Django 3.2.20 on 2023-09-27 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20230927_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledemail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
