# Generated by Django 3.2.20 on 2024-01-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_merge_20240116_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimagerequest',
            name='no_directories',
            field=models.BooleanField(default=False),
        ),
    ]
