# Generated by Django 3.2.20 on 2024-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_producttype_slider'),
        ('user', '0017_variantimagerequest_no_directories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_variants',
            field=models.ManyToManyField(blank=True, to='product.ProductVariant'),
        ),
    ]
