# Generated by Django 3.2.20 on 2024-04-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_sentemail_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
