# Generated by Django 3.2.20 on 2024-05-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='template_name',
            field=models.CharField(choices=[('in-stock', 'In Stock'), ('review-reminder', 'Review Reminder'), ('review-approval', 'Review Approval'), ('review-reply', 'Review Reply'), ('survey-results', 'Survey Results')], max_length=128),
        ),
    ]
