services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers=2 -t 40 --access-logfile -  --access-logformat '%(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %(M)s'
    volumes:
      - /var/volumes/${BRAND_DIR_NAME}/static/:/usr/src/app/static
      - /var/volumes/${BRAND_DIR_NAME}/media/:/usr/src/app/media
    ports:
      - 8000
    expose:
      - 8000
    links:
      - redis:redis
    env_file: .env
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: ${NETWORK_ADDRESS}.2

  postgres:
    image: postgres
    shm_size: 512mb
    ports:
      - 5432
    env_file:
      - .env.postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data/
      - /var/volumes/${BRAND_DIR_NAME}/postgres/:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    networks:
      default:
        ipv4_address: ${NETWORK_ADDRESS}.3

  redis:
    image: redis:latest
    expose:
      - 6379
    restart: unless-stopped
    networks:
      default:
        ipv4_address: ${NETWORK_ADDRESS}.4

volumes:
  postgres-volume:
networks:
  default:
    name: ${BRAND_DIR_NAME}_network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_ADDRESS}.0/24
