# Generated by Django 3.1 on 2020-10-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user_name',
        ),
        migrations.AddField(
            model_name='review',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
