# Generated by Django 3.1 on 2020-09-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='helpful',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reply',
            field=models.ManyToManyField(blank=True, null=True, related_name='review', to='review.Reply', verbose_name='Replies'),
        ),
    ]
