# Generated by Django 3.1 on 2020-10-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20201022_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
