# Generated by Django 3.1 on 2020-10-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20201022_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='verified',
            new_name='approved',
        ),
    ]
