# Generated by Django 3.1 on 2020-12-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_auto_20201208_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='helpful',
            new_name='deslike',
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
