# Generated by Django 3.1 on 2020-12-15 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_auto_20201215_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='deslike',
            new_name='dislike',
        ),
    ]
