# Generated by Django 3.1 on 2021-10-04 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_productreviewquestion'),
        ('review', '0011_reviewimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productreviewquestion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='review.review')),
            ],
        ),
    ]
