# Generated by Django 3.1 on 2021-04-13 12:51

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210217_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image_width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='public/blog_images/', width_field='image_width'),
        ),
    ]
