# Generated by Django 3.1 on 2021-04-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210413_1357'),
        ('blog', '0005_merge_20210219_1145'),
    ]

    operations = [
    ]
