# Generated by Django 3.1 on 2021-05-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210511_1050'),
        ('blog', '0006_merge_20210413_1530'),
    ]

    operations = [
    ]
