# Generated by Django 3.1 on 2021-06-29 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210629_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('collection_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='blog.blogcollection')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='collected_item', to='blog.blogpost')),
            ],
            options={
                'index_together': {('item', 'order')},
            },
        ),
    ]
