# Generated by Django 3.1 on 2020-12-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='content',
        ),
    ]
