from .variant import VariantViewSet
from .tag import TagViewSet
from .product import ProductViewSet
from .single_product import SingleProductViewSet
from .collection import CollectionViewSet
from .product_image import ProductImageViewSet
from .product_type import ProductTypeViewSet
from .favorites_list import FavoriteProductListAPIView
from .favorite import FavoriteProductUpdateAPIView
from .product_edit import ProductEditWebhookAPI
from .spf_recommendation import SPFRecommendationListAPIView
from .favorite_variant import FavoriteVariantUpdateAPIView
from .favorite_variants_list import FavoriteVariantListAPIView
