# Generated by Django 3.1 on 2020-10-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=None)),
                ('active', models.BooleanField(default=False)),
                ('custom_slide', models.BooleanField(default=False)),
                ('custom_code', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField()),
                ('mobile', models.BooleanField()),
                ('slides', models.ManyToManyField(to='web.Slide', verbose_name='slides')),
            ],
        ),
    ]
