# Generated by Django 3.1 on 2020-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(default='', editable=False)),
                ('description', models.CharField(blank=True, default='', max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('image', models.ImageField(blank=True, upload_to='slide/')),
                ('active', models.BooleanField(default=False)),
                ('custom_slide', models.BooleanField(default=False)),
                ('custom_code', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField()),
                ('mobile', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, unique=True)),
                ('value', models.CharField(max_length=350)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('setting', models.ManyToManyField(blank=True, related_name='configuations', to='web.Setting')),
            ],
        ),
    ]
