# Generated by Django 3.1 on 2020-10-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(default='', editable=False)),
                ('description', models.CharField(blank=True, default='', max_length=350, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='slides',
            field=models.ManyToManyField(blank=True, to='web.Slide', verbose_name='slides'),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250, unique=True)),
                ('value', models.CharField(max_length=350)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('setting', models.ManyToManyField(blank=True, related_name='configuations', to='web.Setting')),
            ],
        ),
    ]
