# Generated by Django 3.1 on 2020-10-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20201015_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={},
        ),
        migrations.RemoveField(
            model_name='slide',
            name='order',
        ),
    ]
