# Generated by Django 3.1 on 2020-10-19 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20201015_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderslidesthroughmodel',
            name='slider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_slides', to='web.slider'),
        ),
    ]
