# Generated by Django 3.1 on 2020-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20201019_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='name',
            field=models.CharField(default='', max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
