# Generated by Django 3.1 on 2022-02-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField()),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='contactform',
            name='receivers_email',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='contactform',
            name='sent_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='reason',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='TopBarItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, max_length=512, null=True, upload_to='top-bar-icons/')),
                ('url', models.URLField(blank=True, max_length=256)),
                ('is_active', models.BooleanField()),
                ('position', models.IntegerField()),
                ('top_bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='web.topbar')),
            ],
        ),
    ]
