# Generated by Django 3.1 on 2020-10-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slides',
            field=models.ManyToManyField(blank=True, related_name='slider', to='web.Slide', verbose_name='slides'),
        ),
    ]
