# Generated by Django 3.1 on 2021-03-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_configuration_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='mobile',
        ),
        migrations.AddField(
            model_name='slide',
            name='desktop_image',
            field=models.ImageField(blank=True, upload_to='slide/desktop/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='image_alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='slide',
            name='mobile_image',
            field=models.ImageField(blank=True, upload_to='slide/mobile/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='tablet_image',
            field=models.ImageField(blank=True, upload_to='slide/tablet/'),
        ),
    ]
