# Generated by Django 3.1 on 2022-03-07 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20220307_1610'),
        ('web', '0013_auto_20220221_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=64)),
                ('media_type', models.CharField(max_length=64)),
                ('media_url', models.URLField(max_length=512)),
                ('thumbnail', models.URLField(max_length=512)),
                ('webp', models.URLField(max_length=512)),
                ('caption', models.TextField(blank=True)),
                ('permalink', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='VariantInstagramRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.instagrampost')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
            ],
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='variants',
            field=models.ManyToManyField(related_name='instagram_posts', through='web.VariantInstagramRelation', to='product.ProductVariant'),
        ),
    ]
