# Generated by Django 3.1 on 2023-01-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20220307_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='desktop_image',
            new_name='lg_image',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='tablet_image',
            new_name='md_image',
        ),
        migrations.RenameField(
            model_name='slide',
            old_name='mobile_image',
            new_name='sm_image',
        ),
        migrations.AlterField(
            model_name='slide',
            name='lg_image',
            field=models.ImageField(blank=True, upload_to='slide/lg/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='md_image',
            field=models.ImageField(blank=True, upload_to='slide/md/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='sm_image',
            field=models.ImageField(blank=True, upload_to='slide/sm/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='xl_image',
            field=models.ImageField(blank=True, upload_to='slide/xl/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='xs_image',
            field=models.ImageField(blank=True, upload_to='slide/xs/'),
        ),
    ]
