# Generated by Django 3.2.20 on 2023-09-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_icongroup_icongroupitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icongroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='setting',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
