# Generated by Django 3.2.20 on 2023-11-02 21:58

import common.model_mixins.auto_slugify
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_alter_configuration_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('name', models.CharField(max_length=32)),
                ('text', models.CharField(blank=True, max_length=128)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='menu-images/')),
                ('svg_image', models.FileField(blank=True, max_length=512, null=True, upload_to='menu-svg-images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg'])])),
                ('position', models.PositiveIntegerField(default=0)),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='web.menu')),
            ],
            options={
                'ordering': ('position',),
            },
            bases=(common.model_mixins.auto_slugify.AutoSlugifyMixin, models.Model),
        ),
    ]
