# Generated by Django 3.2.20 on 2023-11-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
