# Generated by Django 3.2.20 on 2024-02-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_contactform_subscribe_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='icongroupitem',
            name='svg_icon_text',
            field=models.TextField(blank=True),
        ),
    ]
