# Generated by Django 3.2.20 on 2024-02-08 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_icongroupitem_svg_icon_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='video',
            field=models.FileField(blank=True, upload_to='slide/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
