# Generated by Django 3.2.20 on 2023-09-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestionchoice',
            name='slug',
            field=models.SlugField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='survey',
            name='slug',
            field=models.SlugField(blank=True, max_length=32, unique=True),
        ),
    ]
