# Generated by Django 3.2.20 on 2023-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20230905_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='image',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='survey_questions/'),
        ),
    ]
