# Generated by Django 3.2.20 on 2023-09-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveyquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyquestion',
            name='image',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to='survey_questions/'),
        ),
    ]
