# Generated by Django 3.1 on 2021-04-12 15:12

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210218_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to=product.models.ProductImage.image_directory_path, width_field='width'),
        ),
    ]
