# Generated by Django 3.1 on 2021-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210505_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='width',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=4179, unique=True, verbose_name='slug'),
        ),
    ]
