# Generated by Django 3.1 on 2021-06-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210602_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Leave it as 0 if you wish for this item to go to the beginning of the list. or set a big number and it will automatically will order it at the end of the list.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=3492, unique=True, verbose_name='slug'),
        ),
    ]
