# Generated by Django 3.1 on 2021-06-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210602_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=7141, unique=True, verbose_name='slug'),
        ),
    ]
