# Generated by Django 3.1 on 2021-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20210602_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=6839, unique=True, verbose_name='slug'),
        ),
    ]
