# Generated by Django 3.1 on 2021-06-02 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20210602_1503'),
        ('product', '0012_merge_20210511_1052'),
    ]

    operations = [
    ]
