# Generated by Django 3.1 on 2021-06-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_merge_20210602_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-image_type']},
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=5820, unique=True, verbose_name='slug'),
        ),
    ]
