# Generated by Django 3.1 on 2021-06-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20210614_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='items',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=2408, unique=True, verbose_name='slug'),
        ),
    ]
