# Generated by Django 3.1 on 2021-06-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210616_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=91, unique=True, verbose_name='slug'),
        ),
    ]
