# Generated by Django 3.1 on 2021-10-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_productreviewquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewQuestionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Review Question',
                'verbose_name_plural': 'Review Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_multiple_choice_question', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Review Question',
                'verbose_name_plural': 'Review Questions',
            },
        ),
        migrations.RemoveField(
            model_name='productreviewquestion',
            name='product',
        ),
    ]
