# Generated by Django 3.1 on 2021-10-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20211011_1046'),
        ('review', '0014_auto_20211011_1046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReviewQuestion',
        ),
        migrations.AddField(
            model_name='reviewquestion',
            name='products',
            field=models.ManyToManyField(related_name='questions', through='product.ProductReviewQuestionRelation', to='product.Product'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='review_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='product.reviewquestion'),
        ),
        migrations.AddField(
            model_name='productreviewquestionrelation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_relations', to='product.product'),
        ),
        migrations.AddField(
            model_name='productreviewquestionrelation',
            name='review_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to='product.reviewquestion', verbose_name='Review Question'),
        ),
    ]
