# Generated by Django 3.1 on 2022-05-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_productvariant_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
