# Generated by Django 3.1 on 2022-05-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_auto_20220504_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='updated',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
