# Generated by Django 3.2 on 2023-06-29 08:50

from django.db import migrations, models
import django.db.models.deletion


def init_through_instances(apps, schema_editor):
    ProductVariant = apps.get_model('product', 'ProductVariant')
    OldVariantIngredientThrough = ProductVariant.ingredients.through
    VariantIngredientThrough = apps.get_model('product', 'VariantIngredientThrough')
    variant_ingredients_to_create = []
    for old_variant_ingredient in OldVariantIngredientThrough.objects.all():
        variant_ingredients_to_create.append(VariantIngredientThrough(
            ingredient=old_variant_ingredient.ingredient,
            variant=old_variant_ingredient.productvariant,
            priority=0,
        ))
    VariantIngredientThrough.objects.bulk_create(variant_ingredients_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_tag_svg_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantIngredientThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ingredient')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant')),
            ],
        ),
        migrations.RunPython(
            code=init_through_instances,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
