# Generated by Django 3.2.20 on 2023-09-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_productvariant_asin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
