# Generated by Django 3.2.20 on 2023-09-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20230905_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='types',
            field=models.ManyToManyField(blank=True, to='product.ProductType', verbose_name='categories'),
        ),
    ]
