# Generated by Django 3.2.20 on 2024-01-31 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_contactform_subscribe_sender'),
        ('product', '0049_alter_product_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.slider'),
        ),
    ]
