# Generated by Django 3.2.20 on 2024-03-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_producttype_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
