# Generated by Django 3.2.20 on 2024-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_productimage_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='secondary',
            field=models.BooleanField(default=False),
        ),
    ]
