# Generated by Django 3.2.20 on 2024-04-15 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_slide_video'),
        ('product', '0052_productimage_secondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.slider'),
        ),
    ]
