# Generated by Django 3.1 on 2020-10-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_review_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
