# Generated by Django 3.1 on 2020-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_auto_20201023_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reply',
            field=models.ManyToManyField(blank=True, related_name='review', to='review.Reply', verbose_name='Replies'),
        ),
    ]
