# Generated by Django 3.1 on 2021-09-20 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_review_opened'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(max_length=64)),
                ('user_cookie', models.CharField(max_length=64)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.review')),
            ],
        ),
    ]
