# Generated by Django 3.1 on 2021-10-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_auto_20211011_1046'),
        ('review', '0013_review_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.reviewquestion'),
        ),
    ]
