# Generated by Django 3.2 on 2023-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_auto_20211011_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='reply',
            name='user_name',
            field=models.CharField(max_length=200),
        ),
    ]
