# Generated by Django 3.2 on 2023-07-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0015_auto_20230623_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
