# Generated by Django 3.2.20 on 2024-05-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0016_alter_review_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reply',
        ),
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
