# Generated by Django 3.1 on 2021-10-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20211011_1554'),
        ('blog', '0011_auto_20210920_0022'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_blogposts',
            field=models.ManyToManyField(blank=True, to='blog.BlogPost'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
