# Generated by Django 3.1 on 2023-03-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20230305_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimagerequest',
            name='image_type',
            field=models.CharField(choices=[('PI', 'Product Image'), ('LS', 'Life Style'), ('RP', 'Range Photo'), ('TX', 'Texture'), ('AN', 'Animation'), ('ST', 'Studio'), ('RS', 'Result'), ('OT', 'Others'), ('ALL', 'All')], default='ALL', max_length=32),
        ),
    ]
