# Generated by Django 3.1 on 2023-05-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20230523_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantimagerequest',
            name='image_angle',
        ),
        migrations.RemoveField(
            model_name='variantimagerequest',
            name='image_format',
        ),
        migrations.RemoveField(
            model_name='variantimagerequest',
            name='image_type',
        ),
    ]
