# Generated by Django 3.1 on 2023-06-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20230523_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('template_name', models.CharField(choices=[('in-stock', 'In Stock')], max_length=128)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('email_id', models.BigIntegerField(blank=True, null=True)),
                ('data', models.TextField(null=True)),
            ],
            options={
                'ordering': ('-sent_date',),
            },
        ),
    ]
