# Generated by Django 3.1 on 2020-12-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_remove_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
