# Generated by Django 3.1 on 2020-10-09 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_auto_20201009_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('excerpt', models.TextField(help_text='A short version of the blog post')),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='static/blog_images')),
                ('published', models.BooleanField(default=False, null=True)),
                ('publish_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('category', models.ManyToManyField(blank=True, to='product.ProductType')),
                ('related_products', models.ManyToManyField(to='product.Product')),
                ('tags', models.ManyToManyField(blank=True, to='product.Tag')),
            ],
        ),
    ]
