# Generated by Django 3.1 on 2021-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210412_1612'),
        ('blog', '0004_auto_20210413_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='A short version of the blog post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
    ]
