# Generated by Django 3.1 on 2021-02-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210217_1052'),
        ('blog', '0004_auto_20210202_1023'),
    ]

    operations = [
    ]
