# Generated by Django 3.1 on 2021-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210413_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image_width',
            field=models.IntegerField(blank=True),
        ),
    ]
