# Generated by Django 3.1 on 2021-06-29 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogcollection_blogcollectionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcollectionitem',
            name='collection_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogcollectionitem', to='blog.blogcollection'),
        ),
    ]
