# Generated by Django 3.1 on 2021-09-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210629_1028'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcollectionitem',
            options={'ordering': ['order']},
        ),
    ]
