# Generated by Django 3.2.20 on 2024-01-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonorder',
            name='earliest_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
