# Generated by Django 3.2.20 on 2024-02-08 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_amazonorder_earliest_delivery_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('shopify_graphql_id', models.CharField(db_index=True, max_length=64)),
                ('order_name', models.CharField(max_length=32)),
                ('financial_status', models.CharField(choices=[('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], max_length=32)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_discounts', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_line_items_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopify_graphql_id', models.CharField(db_index=True, max_length=64)),
                ('product_id', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('variant_id', models.BigIntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
