from .product import ProductAdmin
from .product_variant import ProductVariantAdmin
from .product_image import ProductImageAdmin
from .tag import TagAdmin
from .keyword import KeywordAdmin
from .product_type import ProductTypeAdmin
from .collection import CollectionAdmin
from .collection_item import CollectionItemAdmin
from .stocklist import StockistAdmin
from .where_to_buy import WhereToBuyAdmin
from .ingredient import IngredientAdmin
from .review_question import ReviewQuestionAdmin
