# Generated by Django 3.1 on 2021-02-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_auto_20210104_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=450)),
                ('answer', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('product', models.ManyToManyField(blank=True, to='product.Product')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
