# Generated by Django 3.1 on 2022-05-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20210201_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
