# Generated by Django 3.2.20 on 2024-01-25 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0049_alter_product_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField()),
                ('base_discount_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('extra_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bundles.bundle')),
                ('excluded_variants', models.ManyToManyField(related_name='excluded_bundle_items', to='product.ProductVariant')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='product.product')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='BundleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='bundles/')),
                ('alternate_text', models.CharField(blank=True, max_length=256)),
                ('image_type', models.CharField(choices=[('PI', 'Product Image'), ('LS', 'Life Style'), ('RP', 'Range Photo'), ('TX', 'Texture'), ('AN', 'Animation'), ('ST', 'Studio'), ('RS', 'Result'), ('OT', 'Others')], max_length=2)),
                ('image_angle', models.CharField(choices=[('FRONT', 'Front'), ('BACK', 'Back'), ('ANGLE', 'Angle'), ('TOP', 'Top'), ('RIGHT-SIDE', 'Right Side'), ('LEFT-SIDE', 'Left Side'), ('BOTTOM', 'Bottom'), ('CUSTOM', 'Custom')], max_length=16)),
                ('main', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bundles.bundle')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
