# Generated by Django 3.2.20 on 2024-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_alter_product_types'),
        ('bundles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='base_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='bundleitem',
            name='excluded_variants',
        ),
        migrations.AddField(
            model_name='bundle',
            name='price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AddField(
            model_name='bundleimage',
            name='secondary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bundleitem',
            name='variants',
            field=models.ManyToManyField(related_name='variant_bundle_items', to='product.ProductVariant'),
        ),
    ]
